# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd06faae6d307809116d26299388daa0dbdeacff96fcdf01ea64d1f9a5f091e805ad539b1cd8722ddacbb61d54aee83794c965845bf744de87c703b74a2e5b5

test:
  secret_key_base: 191b925570594f0715473ed16e4a884e9b2debcb2d26a3018084d42b66ebe20cbc9439c42d54f044090aa36092ce8fe03c67dfd6d69fd5f01fa5ac5880fef746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
